name: job summary test

on:
  workflow_dispatch:

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: step1
        uses: actions/checkout@v3

      - name: make a summary
        id: step2
        run: |
          echo "testing"

      - name: make a summary
        id: step3
        run: |
          echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
          ./job_summary.sh

      - name: step tests
        id: step4
        env:
          STDOUT: ${{ join(steps.step2.*, '\n') }}
        run: |
          echo $STDOUT
