name: job summary test

on:
  workflow_dispatch:

jobs:
  summary:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: checkout
        id: step1
        uses: actions/checkout@v3

      - name: echo vars
        run: |
          echo ${LIST_VAR} | tr -d '\n'
        env:
          LIST_VAR: >-
            ${{ vars.LIST }}

      - name: make a summary
        id: step2
        run: |
          echo "testing"
        continue-on-error: true

      - name: make a summary
        id: step3
        run: |
          echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
          ./job_summary.sh

      - name: step tests
        id: step4
        env:
          STDOUT: ${{ join(steps.*, ' ') }}
        run: |
          for i in $STDOUT; do
            echo $i
          done
