name: release version dispatch

on:
  release:
    type:
      - released
jobs:
  release_version_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: trigger workflow dispatch
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "30516147",
              ref: "main",
              inputs: {
                release_version: ${{github.event.release.release_id}}
              }
            })
