name: version check

on:
  workflow_dispatch:
    inputs:
      version:
        description: release tag
        type: string
        required: true

jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check release version
        env:
          GITHUB_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
          RELEASE_VERSION: ${{github.event.inputs.version}}
        run: |
          git checkout -b update/argo-tooling-$RELEASE_VERSION
          git config user.name ${{github.actor}}
          files=$(find . -name "argocd-bootstrap*" |grep -v defaults)
          for file in $files; do
            echo $file
            sed -i "s/\(^.*targetRevision: \)\(.*\)/\1${RELEASE_VERSION}/g" $file
            git commit -m "Updated ${file} with target revision ${RELEASE_VERSION}"
            git push origin update/argo-tooling-$RELEASE_VERSION -u
          done

      - name: submit pr
        uses: actions/github-script@v6
        env:
          RELEASE_VERSION: ${{github.event.inputs.version}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.owner,
              head: "update/argo-tooling-${RELEASE_VERSION}",
              base: "main",
              title: "update/ArgoCd-tooling-release-${RELEASE_VERSION}",
              body: "Updating to ${RELEASE_VERSION} from bip-tooling-argocd release"
            });
