name: version dispatch

on:
  release:
    types:
      - released
      - created

jobs:
  version_dispatch:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: trigger workflow dispatch
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{secrets.DISPATCH_TOKEN}}" \
            https://api.github.com/repos/jaredzieche/github-actions-testing/actions/workflows/version_check.yml/dispatches \
            -d '{"ref":"topic-branch","inputs":{"version":"${{github.event.release.tag_name}}"}'
