name: version check

on:
  workflow_dispatch:
    inputs:
      version:
        description: release tag
        type: string
        required: true

jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check release version
        env:
          RELEASE_VERSION: ${{github.event.inputs.version}}
        run: |
          ./job_summary.sh
